### ISSUE TITLE
Invalid links on HF Model card

### ISSUE THREAD

**Issue by davidgibsonp** [explosion/healthsea#6]
The links on the [Hugging Face model card](https://huggingface.co/explosion/en_healthsea) are incorrect.

> Read more in the [blog post](https://huggingface.co/explosion/en_healthsea/resolve/main/explosion.ai) and visit the [healthsea repository](https://github.com/thomashacker/healthsea) for all training workflows, custom components and training data.

**Comment by thomashacker** [comment]
Oh, you're right, fixed it! Thanks 🎉
